[package]
name = "pathfinder_android_demo"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
egl = "0.2"
gl = "0.14"
jni = "0.15"
lazy_static = "1.3"

[dependencies.pathfinder_demo]
path = "../../common"

[dependencies.pathfinder_geometry]
path = "../../../geometry"

[dependencies.pathfinder_gl]
path = "../../../gl"

[dependencies.pathfinder_gpu]
path = "../../../gpu"

[dependencies.pathfinder_resources]
path = "../../../resources"
