[package]
name = "canvas_minimal"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[dependencies]
gl = "0.14"

[dependencies.euclid]
version = "0.20"
features = []

[dependencies.pathfinder_canvas]
path = "../../canvas"

[dependencies.pathfinder_color]
path = "../../color"

[dependencies.pathfinder_content]
path = "../../content"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_gl]
path = "../../gl"

[dependencies.pathfinder_gpu]
path = "../../gpu"

[dependencies.pathfinder_renderer]
path = "../../renderer"

[dependencies.pathfinder_resources]
path = "../../resources"

[dependencies.surfman]
version = "0.4.3"
features = ["sm-winit", "sm-x11"]

[dependencies.winit]
version = "0.24"
